language: cpp
#sudo: false
install:
- sudo apt-get install git cmake dos2unix libosmesa-dev
script:
- make -C auto clobber
- make extensions
- make dist-src
- make clean; SYSTEM=linux        make 
- pushd build/cmake; git clean -xdf .; cmake -G 'Unix Makefiles' .                ; make; popd
addons:
  artifacts:
    bucket: glew
    s3_region: "us-east-1"
    paths:
    - $(ls *.zip *.tgz | tr "\n" ":")
    - $(find doc -type f | tr "\n" ":")
